version: "3.8"

services:
    backend:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

volumes:
    postgres_data:
